//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEmploye
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int ID_EMPLOYE { get; set; }
        public int Matricule { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public int NbrEnfant { get; set; }
        public string Anciennete { get; set; }
        public int Salaire_Base { get; set; }
        public string Statut { get; set; }
        public int PrimeS { get; set; }
        public int Prime { get; set; }
        public int Ipres { get; set; }
        public int ID_SERVICE { get; set; }
    
        public virtual Service_Emp Service_Emp { get; set; }
    }
}
